// Generated by Apple Swift version 3.1 (swiftlang-802.0.51 clang-802.0.41)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if defined(__has_attribute) && __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

SWIFT_CLASS("_TtC12meposconnect18AbstractBLProducer")
@interface AbstractBLProducer : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


/// A link decoder is a implementation of a ByteLump processor that consumes
/// frames coming in from the serial link, strips and checks the CRC and
/// framing details, and forwards on to whatever consumers are registered.
/// <p>
/// This class does buffer incoming bytes, and notifies consumers only when a
/// complete full and accurate frame has been unpacked.
SWIFT_CLASS("_TtC12meposconnect13LinkDecoder16")
@interface LinkDecoder16 : AbstractBLProducer
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LENGTH_8BIT;)
+ (NSInteger)LENGTH_8BIT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LENGTH_12BIT;)
+ (NSInteger)LENGTH_12BIT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LENGTH_16BIT;)
+ (NSInteger)LENGTH_16BIT SWIFT_WARN_UNUSED_RESULT;
/// A link decoder only has one input and output channel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setCRCEnableWithB:(BOOL)b;
- (void)setLengthSizeWithI:(NSInteger)i;
@end

@protocol MePOSConnectionManager;
@class MePOSReceipt;
@protocol MePOSPrinterCallback;

SWIFT_CLASS("_TtC12meposconnect5MePOS")
@interface MePOS : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger CUT_TYPE_FULL;)
+ (NSInteger)CUT_TYPE_FULL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger CUT_TYPE_PARTIAL;)
+ (NSInteger)CUT_TYPE_PARTIAL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_STYLE_NONE;)
+ (NSInteger)TEXT_STYLE_NONE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_STYLE_BOLD;)
+ (NSInteger)TEXT_STYLE_BOLD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_STYLE_ITALIC;)
+ (NSInteger)TEXT_STYLE_ITALIC SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_STYLE_UNDERLINED;)
+ (NSInteger)TEXT_STYLE_UNDERLINED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_STYLE_INVERSE;)
+ (NSInteger)TEXT_STYLE_INVERSE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_SIZE_NORMAL;)
+ (NSInteger)TEXT_SIZE_NORMAL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_SIZE_WIDE;)
+ (NSInteger)TEXT_SIZE_WIDE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_POSITION_LEFT;)
+ (NSInteger)TEXT_POSITION_LEFT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_POSITION_CENTER;)
+ (NSInteger)TEXT_POSITION_CENTER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_POSITION_RIGHT;)
+ (NSInteger)TEXT_POSITION_RIGHT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger BARCODE_TYPE_UPCA;)
+ (NSInteger)BARCODE_TYPE_UPCA SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger BARCODE_TYPE_CODE39;)
+ (NSInteger)BARCODE_TYPE_CODE39 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger BARCODE_TYPE_PDF417;)
+ (NSInteger)BARCODE_TYPE_PDF417 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger BARCODE_HRI_NONE;)
+ (NSInteger)BARCODE_HRI_NONE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger BARCODE_HRI_ABOVE;)
+ (NSInteger)BARCODE_HRI_ABOVE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger BARCODE_HRI_BELOW;)
+ (NSInteger)BARCODE_HRI_BELOW SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger BARCODE_HRI_BOTH;)
+ (NSInteger)BARCODE_HRI_BOTH SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger CASH_DRAWER_STATUS_OPENED;)
+ (NSInteger)CASH_DRAWER_STATUS_OPENED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger CASH_DRAWER_STATUS_CLOSED;)
+ (NSInteger)CASH_DRAWER_STATUS_CLOSED SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (id <MePOSConnectionManager> _Nonnull)getConnectionManager SWIFT_WARN_UNUSED_RESULT;
- (void)setDiagnosticLedWithPosition:(NSInteger)position colour:(NSInteger)colour;
- (void)setCosmeticLedColWithColour:(NSInteger)colour;
- (BOOL)printerBusy SWIFT_WARN_UNUSED_RESULT;
- (void)printWithReceipt:(MePOSReceipt * _Nonnull)receipt callback:(id <MePOSPrinterCallback> _Nullable)callback;
- (void)printWithReceipt:(MePOSReceipt * _Nonnull)receipt;
- (BOOL)enableUSBAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)disableUSBAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)isMePOSConnected SWIFT_WARN_UNUSED_RESULT;
- (void)printConfigPage;
- (NSString * _Nonnull)getFWVersion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSerialNumber SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC12meposconnect15MePOSColorCodes")
@interface MePOSColorCodes : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_OFF;)
+ (NSInteger)LED_OFF SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_GREEN;)
+ (NSInteger)LED_GREEN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_RED;)
+ (NSInteger)LED_RED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_AMBER;)
+ (NSInteger)LED_AMBER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger COSMETIC_OFF;)
+ (NSInteger)COSMETIC_OFF SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger COSMETIC_BLUE;)
+ (NSInteger)COSMETIC_BLUE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger COSMETIC_GREEN;)
+ (NSInteger)COSMETIC_GREEN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger COSMETIC_CYAN;)
+ (NSInteger)COSMETIC_CYAN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger COSMETIC_RED;)
+ (NSInteger)COSMETIC_RED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger COSMETIC_MAGENTA;)
+ (NSInteger)COSMETIC_MAGENTA SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger COSMETIC_YELLOW;)
+ (NSInteger)COSMETIC_YELLOW SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger COSMETIC_WHITE;)
+ (NSInteger)COSMETIC_WHITE SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12meposconnect28MePOSConfigurationController")
@interface MePOSConfigurationController : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP12meposconnect22MePOSConnectionManager_")
@protocol MePOSConnectionManager
- (NSInteger)getConnectionStatus SWIFT_WARN_UNUSED_RESULT;
- (void)setConnectionIPAddressWithIPAddress:(NSString * _Nonnull)IPAddress;
- (NSString * _Nonnull)getConnectionIPAddress SWIFT_WARN_UNUSED_RESULT;
- (void)disconnect;
@end


SWIFT_CLASS("_TtC12meposconnect19MePOSDiagnosticLEDS")
@interface MePOSDiagnosticLEDS : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_POWER;)
+ (NSInteger)LED_POWER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_NETWORK;)
+ (NSInteger)LED_NETWORK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_TABLET;)
+ (NSInteger)LED_TABLET SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_PED;)
+ (NSInteger)LED_PED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_PRINTER;)
+ (NSInteger)LED_PRINTER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_USB1;)
+ (NSInteger)LED_USB1 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_USB2;)
+ (NSInteger)LED_USB2 SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, MePOSError) {
  MePOSErrorGENERIC = 0,
  MePOSErrorPRINTER_NOT_RESPONDING = 1,
  MePOSErrorCASH_DRAWER_STATUS_MESSAGE_NOT_RECEIVED = 2,
};
static NSString * _Nonnull const MePOSErrorDomain = @"meposconnect.MePOSError";

typedef SWIFT_ENUM(NSInteger, MePOSMessageResponse) {
  MePOSMessageResponsePRINT_ACKNOWLEDGED = 0,
  MePOSMessageResponseWIFI_ACKNOWLEDGED = 1,
  MePOSMessageResponseIO_CHANGE_OK = 2,
  MePOSMessageResponsePRINTER_STATUS_OK = 3,
  MePOSMessageResponsePRINTER_STATUS_NOT_READY = 4,
  MePOSMessageResponseCASH_DRAWER_STATE_1 = 5,
  MePOSMessageResponseCASH_DRAWER_STATE_2 = 6,
  MePOSMessageResponseERROR_PRINTER_NOT_OK = 7,
  MePOSMessageResponseUNKNOWN = 8,
};


SWIFT_PROTOCOL("_TtP12meposconnect20MePOSPrinterCallback_")
@protocol MePOSPrinterCallback
- (void)onPrinterStartedWithIpAddress:(NSString * _Nonnull)ipAddress;
- (void)onPrinterCompletedWithIpAddress:(NSString * _Nonnull)ipAddress;
- (void)onPrinterErrorWithError:(enum MePOSError)error;
@end


SWIFT_CLASS("_TtC12meposconnect22MePOSPrinterController")
@interface MePOSPrinterController : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class MePOSReceiptLine;

SWIFT_CLASS("_TtC12meposconnect12MePOSReceipt")
@interface MePOSReceipt : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSArray<MePOSReceiptLine *> * _Nonnull)getLines SWIFT_WARN_UNUSED_RESULT;
- (void)addLineWithLine:(MePOSReceiptLine * _Nonnull)line;
- (NSInteger)getCutType SWIFT_WARN_UNUSED_RESULT;
- (void)setCutTypeWithCutType:(NSInteger)cutType;
- (NSInteger)getHeaderFeed SWIFT_WARN_UNUSED_RESULT;
- (void)setHeaderFeedWithHeaderFeed:(NSInteger)headerFeed;
- (NSInteger)getFooterFeed SWIFT_WARN_UNUSED_RESULT;
- (void)setFooterFeedWithFooterFeed:(NSInteger)footerFeed;
@end

enum MePOSReceiptLineType : NSInteger;

SWIFT_CLASS("_TtC12meposconnect16MePOSReceiptLine")
@interface MePOSReceiptLine : NSObject
@property (nonatomic) enum MePOSReceiptLineType lineType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12meposconnect23MePOSReceiptBarcodeLine")
@interface MePOSReceiptBarcodeLine : MePOSReceiptLine
@property (nonatomic) NSInteger type;
@property (nonatomic) NSInteger hri;
@property (nonatomic) double height;
@property (nonatomic, copy) NSString * _Nonnull data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(NSInteger)type data:(NSString * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(NSInteger)type hri:(NSInteger)hri height:(double)height data:(NSString * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (void)setTypeWithType:(NSInteger)type;
- (void)setDataWithData:(NSString * _Nonnull)data;
- (void)setHeightWithHeight:(double)height;
- (void)setHriWithHri:(NSInteger)hri;
@end


SWIFT_CLASS("_TtC12meposconnect20MePOSReceiptFeedLine")
@interface MePOSReceiptFeedLine : MePOSReceiptLine
@property (nonatomic) NSInteger lines;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLines:(NSInteger)lines OBJC_DESIGNATED_INITIALIZER;
- (void)setLinesWithLines:(NSInteger)lines;
@end

@class CIImage;

SWIFT_CLASS("_TtC12meposconnect21MePOSReceiptImageLine")
@interface MePOSReceiptImageLine : MePOSReceiptLine
@property (nonatomic, strong) CIImage * _Nonnull image;
- (nonnull instancetype)initWithImage:(CIImage * _Nonnull)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


typedef SWIFT_ENUM(NSInteger, MePOSReceiptLineType) {
  MePOSReceiptLineTypePRICE = 0,
  MePOSReceiptLineTypeTEXT = 1,
  MePOSReceiptLineTypeIMAGE = 2,
  MePOSReceiptLineTypeIMAGE_BUFFER = 3,
  MePOSReceiptLineTypeBARCODE = 4,
  MePOSReceiptLineTypeFEED = 5,
  MePOSReceiptLineTypeSINGLE_CHAR = 6,
};


SWIFT_CLASS("_TtC12meposconnect21MePOSReceiptPriceLine")
@interface MePOSReceiptPriceLine : MePOSReceiptLine
@property (nonatomic, copy) NSString * _Nonnull leftText;
@property (nonatomic, copy) NSString * _Nonnull rightText;
@property (nonatomic) NSInteger leftStyle;
@property (nonatomic) NSInteger rightStyle;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLeftText:(NSString * _Nonnull)leftText leftStyle:(NSInteger)leftStyle rightText:(NSString * _Nonnull)rightText rightStyle:(NSInteger)rightStyle OBJC_DESIGNATED_INITIALIZER;
- (void)setLeftTextWithLeftText:(NSString * _Nonnull)leftText style:(NSInteger)style;
- (void)setRightTextWithRightText:(NSString * _Nonnull)rightText style:(NSInteger)style;
@end


SWIFT_CLASS("_TtC12meposconnect26MePOSReceiptSingleCharLine")
@interface MePOSReceiptSingleCharLine : MePOSReceiptLine
@property (nonatomic, copy) NSString * _Nonnull chr;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithChr:(NSString * _Nonnull)chr OBJC_DESIGNATED_INITIALIZER;
- (void)setCharWithChr:(NSString * _Nonnull)chr;
@end


SWIFT_CLASS("_TtC12meposconnect20MePOSReceiptTextLine")
@interface MePOSReceiptTextLine : MePOSReceiptLine
@property (nonatomic, copy) NSString * _Nonnull text;
@property (nonatomic) NSInteger style;
@property (nonatomic) NSInteger size;
@property (nonatomic) NSInteger position;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithText:(NSString * _Nonnull)text style:(NSInteger)style size:(NSInteger)size position:(NSInteger)position OBJC_DESIGNATED_INITIALIZER;
- (void)setTextWithText:(NSString * _Nonnull)text style:(NSInteger)style size:(NSInteger)size position:(NSInteger)position;
@end


SWIFT_CLASS("_TtC12meposconnect14MessageBuilder")
@interface MessageBuilder : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t NODE_MEPOS_HOST_DEVICE;)
+ (int8_t)NODE_MEPOS_HOST_DEVICE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t NODE_MEPOS_BRAIN_UNIT;)
+ (int8_t)NODE_MEPOS_BRAIN_UNIT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t NODE_WIFI_MODULE;)
+ (int8_t)NODE_WIFI_MODULE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t CHANNEL_USB_LINK;)
+ (int8_t)CHANNEL_USB_LINK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t CHANNEL_USART0_WIFI;)
+ (int8_t)CHANNEL_USART0_WIFI SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t CHANNEL_UART1_PRINTER;)
+ (int8_t)CHANNEL_UART1_PRINTER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t CHANNEL_USART1_TOWER;)
+ (int8_t)CHANNEL_USART1_TOWER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t CHANNEL_SPI_UART_A_DE9;)
+ (int8_t)CHANNEL_SPI_UART_A_DE9 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t CHANNEL_SPI_UART_B_RJ45;)
+ (int8_t)CHANNEL_SPI_UART_B_RJ45 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t CHANNEL_DEVICE_ADMINISTRATIVE_FUNCTIONS;)
+ (int8_t)CHANNEL_DEVICE_ADMINISTRATIVE_FUNCTIONS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t CHANNEL_IO_BUTTONS_LEDS;)
+ (int8_t)CHANNEL_IO_BUTTONS_LEDS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t CHANNEL_CASH_DRAWER;)
+ (int8_t)CHANNEL_CASH_DRAWER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t GET_VERSION_COMMAND;)
+ (int8_t)GET_VERSION_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t GET_SERIAL_NUMBER_COMMAND;)
+ (int8_t)GET_SERIAL_NUMBER_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t SET_SYSTEM_INFO_COMMAND;)
+ (int8_t)SET_SYSTEM_INFO_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t GET_SYSTEM_INFO_COMMAND;)
+ (int8_t)GET_SYSTEM_INFO_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t GET_CLOCK_COMMAND;)
+ (int8_t)GET_CLOCK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t SET_CLOCK_COMMAND;)
+ (int8_t)SET_CLOCK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t NOTIFICATION_RAW_DATA;)
+ (int8_t)NOTIFICATION_RAW_DATA SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t SET_PORT_CONTROL_STATE_COMMAND;)
+ (int8_t)SET_PORT_CONTROL_STATE_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t GET_PORT_CONTROL_STATE_COMMAND;)
+ (int8_t)GET_PORT_CONTROL_STATE_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t RESET_COMMAND;)
+ (int8_t)RESET_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t PING_COMMAND;)
+ (int8_t)PING_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t DO_TEST_COMMAND;)
+ (int8_t)DO_TEST_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) int8_t GET_SET_REG_OR_IO_LEVEL;)
+ (int8_t)GET_SET_REG_OR_IO_LEVEL SWIFT_WARN_UNUSED_RESULT;
- (MessageBuilder * _Nonnull)withSourceChannelWithChannel:(int8_t)channel SWIFT_WARN_UNUSED_RESULT;
- (MessageBuilder * _Nonnull)withSourceNodeWithNode:(int8_t)node SWIFT_WARN_UNUSED_RESULT;
- (MessageBuilder * _Nonnull)withDestinyChannelWithChannel:(int8_t)channel SWIFT_WARN_UNUSED_RESULT;
- (MessageBuilder * _Nonnull)withDestinynodeWithNode:(int8_t)node SWIFT_WARN_UNUSED_RESULT;
- (MessageBuilder * _Nonnull)withTagNumberWithTagNumber:(int8_t)tagNumber SWIFT_WARN_UNUSED_RESULT;
- (MessageBuilder * _Nonnull)withTagNumberIntWithTagNumber:(NSInteger)tagNumber SWIFT_WARN_UNUSED_RESULT;
- (MessageBuilder * _Nonnull)withTypeWithType:(int8_t)type SWIFT_WARN_UNUSED_RESULT;
/// this method is used to build the message and return the data.
/// @return
- (NSArray<NSNumber *> * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC12meposconnect12PrinterQueue")
@interface PrinterQueue : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL IS_PRINTING;)
+ (BOOL)IS_PRINTING SWIFT_WARN_UNUSED_RESULT;
+ (void)setIS_PRINTING:(BOOL)value;
- (nonnull instancetype)initWithController:(MePOSPrinterController * _Nonnull)controller OBJC_DESIGNATED_INITIALIZER;
- (void)addToQueueWithReceipt:(MePOSReceipt * _Nonnull)receipt;
- (void)addToQueueWithReceipt:(MePOSReceipt * _Nonnull)receipt callback:(id <MePOSPrinterCallback> _Nullable)callback;
- (void)runPrintingRoutine;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC12meposconnect15ReceiptComposer")
@interface ReceiptComposer : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12meposconnect15ResponseMatcher")
@interface ResponseMatcher : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (enum MePOSMessageResponse)processResponseFromMePOSWithBuffer:(NSArray<NSNumber *> * _Nonnull)buffer SWIFT_WARN_UNUSED_RESULT;
- (enum MePOSMessageResponse)processSysInfoWithMessageSpecific:(NSArray<NSNumber *> * _Nonnull)messageSpecific SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isAcknowledgedWithResponse:(enum MePOSMessageResponse)response SWIFT_WARN_UNUSED_RESULT;
@end

#pragma clang diagnostic pop
