// Generated by Apple Swift version 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_attribute(external_source_symbol)
# define SWIFT_STRINGIFY(str) #str
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name) _Pragma(SWIFT_STRINGIFY(clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in=module_name, generated_declaration))), apply_to=any(function, enum, objc_interface, objc_category, objc_protocol))))
# define SWIFT_MODULE_NAMESPACE_POP _Pragma("clang attribute pop")
#else
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name)
# define SWIFT_MODULE_NAMESPACE_POP
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

SWIFT_MODULE_NAMESPACE_PUSH("meposconnect")

SWIFT_CLASS("_TtC12meposconnect18AbstractBLProducer")
@interface AbstractBLProducer : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


/// A link decoder is a implementation of a ByteLump processor that consumes
/// frames coming in from the serial link, strips and checks the CRC and
/// framing details, and forwards on to whatever consumers are registered.
/// <p>
/// This class does buffer incoming bytes, and notifies consumers only when a
/// complete full and accurate frame has been unpacked.
SWIFT_CLASS("_TtC12meposconnect13LinkDecoder16")
@interface LinkDecoder16 : AbstractBLProducer
@end

enum MePOSConnectionType : NSInteger;
@protocol MePOSConnectionManager;
@class MePOSReceipt;
@protocol MePOSPrinterCallback;

SWIFT_CLASS("_TtC12meposconnect5MePOS")
@interface MePOS : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger CUT_TYPE_FULL;)
+ (NSInteger)CUT_TYPE_FULL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger CUT_TYPE_PARTIAL;)
+ (NSInteger)CUT_TYPE_PARTIAL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_STYLE_NONE;)
+ (NSInteger)TEXT_STYLE_NONE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_STYLE_BOLD;)
+ (NSInteger)TEXT_STYLE_BOLD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_STYLE_ITALIC;)
+ (NSInteger)TEXT_STYLE_ITALIC SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_STYLE_UNDERLINED;)
+ (NSInteger)TEXT_STYLE_UNDERLINED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_STYLE_INVERSE;)
+ (NSInteger)TEXT_STYLE_INVERSE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_SIZE_NORMAL;)
+ (NSInteger)TEXT_SIZE_NORMAL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_SIZE_WIDE;)
+ (NSInteger)TEXT_SIZE_WIDE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_POSITION_LEFT;)
+ (NSInteger)TEXT_POSITION_LEFT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_POSITION_CENTER;)
+ (NSInteger)TEXT_POSITION_CENTER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TEXT_POSITION_RIGHT;)
+ (NSInteger)TEXT_POSITION_RIGHT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger BARCODE_TYPE_UPCA;)
+ (NSInteger)BARCODE_TYPE_UPCA SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger BARCODE_TYPE_CODE39;)
+ (NSInteger)BARCODE_TYPE_CODE39 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger BARCODE_TYPE_PDF417;)
+ (NSInteger)BARCODE_TYPE_PDF417 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger BARCODE_HRI_NONE;)
+ (NSInteger)BARCODE_HRI_NONE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger BARCODE_HRI_ABOVE;)
+ (NSInteger)BARCODE_HRI_ABOVE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger BARCODE_HRI_BELOW;)
+ (NSInteger)BARCODE_HRI_BELOW SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger BARCODE_HRI_BOTH;)
+ (NSInteger)BARCODE_HRI_BOTH SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger CASH_DRAWER_STATUS_OPENED;)
+ (NSInteger)CASH_DRAWER_STATUS_OPENED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger CASH_DRAWER_STATUS_CLOSED;)
+ (NSInteger)CASH_DRAWER_STATUS_CLOSED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_CODE_GENERAL;)
+ (NSInteger)ERROR_CODE_GENERAL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithMePOSType:(enum MePOSConnectionType)withMePOSType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init;
- (id <MePOSConnectionManager> _Nonnull)getConnectionManager SWIFT_WARN_UNUSED_RESULT;
- (BOOL)openCashDrawer SWIFT_WARN_UNUSED_RESULT;
- (BOOL)openCashDrawerWithValidateCashDrawerStatus:(BOOL)validateCashDrawerStatus SWIFT_WARN_UNUSED_RESULT;
- (void)setDiagnosticLedWithPosition:(NSInteger)position colour:(NSInteger)colour;
- (void)setCosmeticLedColWithColour:(NSInteger)colour;
- (BOOL)printerBusy SWIFT_WARN_UNUSED_RESULT;
- (void)printWithReceipt:(MePOSReceipt * _Nonnull)receipt callback:(id <MePOSPrinterCallback> _Nullable)callback;
- (void)printWithReceipt:(MePOSReceipt * _Nonnull)receipt;
- (BOOL)enableUSBAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)disableUSBAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)enableCosmeticLEDButtonAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)disableCosmeticLEDButtonAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)isMePOSConnected SWIFT_WARN_UNUSED_RESULT;
- (BOOL)printRawWithRawData:(NSString * _Nonnull)rawData error:(NSError * _Nullable * _Nullable)error;
- (BOOL)serialRawWithRawData:(NSString * _Nonnull)rawData error:(NSError * _Nullable * _Nullable)error;
- (void)printConfigPage;
- (NSString * _Nonnull)getFWVersion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSerialNumber SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC12meposconnect15MePOSColorCodes")
@interface MePOSColorCodes : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_OFF;)
+ (NSInteger)LED_OFF SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_GREEN;)
+ (NSInteger)LED_GREEN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_RED;)
+ (NSInteger)LED_RED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_AMBER;)
+ (NSInteger)LED_AMBER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger COSMETIC_OFF;)
+ (NSInteger)COSMETIC_OFF SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger COSMETIC_BLUE;)
+ (NSInteger)COSMETIC_BLUE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger COSMETIC_GREEN;)
+ (NSInteger)COSMETIC_GREEN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger COSMETIC_CYAN;)
+ (NSInteger)COSMETIC_CYAN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger COSMETIC_RED;)
+ (NSInteger)COSMETIC_RED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger COSMETIC_MAGENTA;)
+ (NSInteger)COSMETIC_MAGENTA SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger COSMETIC_YELLOW;)
+ (NSInteger)COSMETIC_YELLOW SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger COSMETIC_WHITE;)
+ (NSInteger)COSMETIC_WHITE SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12meposconnect28MePOSConfigurationController")
@interface MePOSConfigurationController : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP12meposconnect22MePOSConnectionManager_")
@protocol MePOSConnectionManager
- (NSInteger)getConnectionStatus SWIFT_WARN_UNUSED_RESULT;
- (void)setConnectionIPAddressWithIPAddress:(NSString * _Nonnull)IPAddress;
- (void)setConnectionPortWithPort:(int32_t)port;
- (NSString * _Nonnull)getConnectionIPAddress SWIFT_WARN_UNUSED_RESULT;
- (enum MePOSConnectionType)getType SWIFT_WARN_UNUSED_RESULT;
- (void)disconnect;
@end

typedef SWIFT_ENUM(NSInteger, MePOSConnectionType) {
  MePOSConnectionTypeWIFI = 0,
  MePOSConnectionTypeGENERIC_WIFI = 1,
};


SWIFT_CLASS("_TtC12meposconnect19MePOSDiagnosticLEDS")
@interface MePOSDiagnosticLEDS : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_POWER;)
+ (NSInteger)LED_POWER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_NETWORK;)
+ (NSInteger)LED_NETWORK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_TABLET;)
+ (NSInteger)LED_TABLET SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_PED;)
+ (NSInteger)LED_PED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_PRINTER;)
+ (NSInteger)LED_PRINTER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_USB1;)
+ (NSInteger)LED_USB1 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LED_USB2;)
+ (NSInteger)LED_USB2 SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, MePOSError) {
  MePOSErrorMeposNotFound = 0,
  MePOSErrorPrinterBusy = 1,
  MePOSErrorCashDrawerStatusMessageNotReceived = 2,
  MePOSErrorMethodNotSupportedForGenericPrinters = 3,
  MePOSErrorGeneric = 4,
};
static NSString * _Nonnull const MePOSErrorDomain = @"meposconnect.MePOSError";

typedef SWIFT_ENUM(NSInteger, MePOSMessageResponse) {
  MePOSMessageResponsePRINT_ACKNOWLEDGED = 0,
  MePOSMessageResponseWIFI_ACKNOWLEDGED = 1,
  MePOSMessageResponseIO_CHANGE = 2,
  MePOSMessageResponsePRINTER_STATUS_OK = 3,
  MePOSMessageResponsePRINTER_STATUS_NOT_READY = 4,
  MePOSMessageResponseCASH_DRAWER_STATE_1 = 5,
  MePOSMessageResponseCASH_DRAWER_STATE_2 = 6,
  MePOSMessageResponseERROR_PRINTER_NOT_OK = 7,
  MePOSMessageResponseUNKNOWN = 8,
};


SWIFT_PROTOCOL("_TtP12meposconnect20MePOSPrinterCallback_")
@protocol MePOSPrinterCallback
- (void)onPrinterStartedWithIpAddress:(NSString * _Nonnull)ipAddress;
- (void)onPrinterCompletedWithIpAddress:(NSString * _Nonnull)ipAddress;
- (void)onPrinterErrorWithError:(enum MePOSError)error;
@end


SWIFT_CLASS("_TtC12meposconnect22MePOSPrinterController")
@interface MePOSPrinterController : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class MePOSReceiptLine;

SWIFT_CLASS("_TtC12meposconnect12MePOSReceipt")
@interface MePOSReceipt : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSArray<MePOSReceiptLine *> * _Nonnull)getLines SWIFT_WARN_UNUSED_RESULT;
- (void)addLineWithLine:(MePOSReceiptLine * _Nonnull)line;
- (NSInteger)getCutType SWIFT_WARN_UNUSED_RESULT;
- (void)setCutTypeWithCutType:(NSInteger)cutType;
- (NSInteger)getHeaderFeed SWIFT_WARN_UNUSED_RESULT;
- (void)setHeaderFeedWithHeaderFeed:(NSInteger)headerFeed;
- (NSInteger)getFooterFeed SWIFT_WARN_UNUSED_RESULT;
- (void)setFooterFeedWithFooterFeed:(NSInteger)footerFeed;
- (NSInteger)getFeedAfterCut SWIFT_WARN_UNUSED_RESULT;
- (void)setFeedAfterCutWithFeedLines:(NSInteger)feedLines;
@end


SWIFT_CLASS("_TtC12meposconnect16MePOSReceiptLine")
@interface MePOSReceiptLine : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12meposconnect23MePOSReceiptBarcodeLine")
@interface MePOSReceiptBarcodeLine : MePOSReceiptLine
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(NSInteger)type data:(NSString * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(NSInteger)type hri:(NSInteger)hri height:(double)height data:(NSString * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (void)setTypeWithType:(NSInteger)type;
- (void)setDataWithData:(NSString * _Nonnull)data;
- (void)setHeightWithHeight:(double)height;
- (void)setHriWithHri:(NSInteger)hri;
@end


SWIFT_CLASS("_TtC12meposconnect20MePOSReceiptFeedLine")
@interface MePOSReceiptFeedLine : MePOSReceiptLine
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLines:(NSInteger)lines OBJC_DESIGNATED_INITIALIZER;
- (void)setLinesWithLines:(NSInteger)lines;
@end

@class CIImage;

SWIFT_CLASS("_TtC12meposconnect21MePOSReceiptImageLine")
@interface MePOSReceiptImageLine : MePOSReceiptLine
- (nonnull instancetype)initWithImage:(CIImage * _Nonnull)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


typedef SWIFT_ENUM(NSInteger, MePOSReceiptLineType) {
  MePOSReceiptLineTypePRICE = 0,
  MePOSReceiptLineTypeTEXT = 1,
  MePOSReceiptLineTypeIMAGE = 2,
  MePOSReceiptLineTypeIMAGE_BUFFER = 3,
  MePOSReceiptLineTypeBARCODE = 4,
  MePOSReceiptLineTypeFEED = 5,
  MePOSReceiptLineTypeSINGLE_CHAR = 6,
};


SWIFT_CLASS("_TtC12meposconnect21MePOSReceiptPriceLine")
@interface MePOSReceiptPriceLine : MePOSReceiptLine
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLeftText:(NSString * _Nonnull)leftText leftStyle:(NSInteger)leftStyle rightText:(NSString * _Nonnull)rightText rightStyle:(NSInteger)rightStyle OBJC_DESIGNATED_INITIALIZER;
- (void)setLeftTextWithLeftText:(NSString * _Nonnull)leftText style:(NSInteger)style;
- (void)setRightTextWithRightText:(NSString * _Nonnull)rightText style:(NSInteger)style;
@end


SWIFT_CLASS("_TtC12meposconnect26MePOSReceiptSingleCharLine")
@interface MePOSReceiptSingleCharLine : MePOSReceiptLine
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithChr:(NSString * _Nonnull)chr OBJC_DESIGNATED_INITIALIZER;
- (void)setCharWithChr:(NSString * _Nonnull)chr;
@end


SWIFT_CLASS("_TtC12meposconnect20MePOSReceiptTextLine")
@interface MePOSReceiptTextLine : MePOSReceiptLine
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithText:(NSString * _Nonnull)text style:(NSInteger)style size:(NSInteger)size position:(NSInteger)position OBJC_DESIGNATED_INITIALIZER;
- (void)setTextWithText:(NSString * _Nonnull)text style:(NSInteger)style size:(NSInteger)size position:(NSInteger)position;
@end


SWIFT_CLASS("_TtC12meposconnect14MessageBuilder")
@interface MessageBuilder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC12meposconnect12PrinterQueue")
@interface PrinterQueue : NSObject
- (void)runPrintingRoutine;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC12meposconnect15ReceiptComposer")
@interface ReceiptComposer : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12meposconnect15ResponseMatcher")
@interface ResponseMatcher : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
